load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "carafe",
    srcs = ["homebrew_formulae.go"],
    importpath = "github.com/macadmins/osquery-extension/tables/carafe",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/utils",
        "@com_github_osquery_osquery_go//plugin/table",
    ],
)

go_test(
    name = "carafe_test",
    srcs = ["homebrew_formulae_test.go"],
    embed = [":carafe"],
    deps = [
        "@com_github_osquery_osquery_go//plugin/table",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
